// GENERATED by tools/gen.py from sheets/*.json - edit the sheets, not this file.
class CfgRemoteExec {
    class Functions {
        mode = 1;
        jip = 0;
        class BTD_fnc_requestBuild { allowedTargets = 2; };
        class BTD_fnc_requestUpgrade { allowedTargets = 2; };
        class BTD_fnc_requestSell { allowedTargets = 2; };
        class BTD_fnc_requestRound { allowedTargets = 2; };
        class BTD_fnc_requestSpeed { allowedTargets = 2; };
        class BTD_fnc_requestSnapshot { allowedTargets = 2; };
        class BTD_fnc_playerHit { allowedTargets = 2; };
        class BTD_fnc_playerBlast { allowedTargets = 2; };
        class BTD_fnc_clientBatch { allowedTargets = 0; };
        class BTD_fnc_clientSnapshot { allowedTargets = 0; };
        class BTD_fnc_clientEnd { allowedTargets = 0; };
        class BTD_fnc_notify { allowedTargets = 0; };
    };
    class Commands { mode = 0; };
};
