// GENERATED by tools/gen.py from sheets/hooks.json
class CfgFunctions {
    class BO {
        tag = "BO";
        class core {
            file = "\z\bloonsops\addons\main\functions";
            class initData { preInit = 1;};
            class now {};
            class initServer {};
            class buildPath {};
            class drawTrack {};
            class pathPos {};
            class initPlayer {};
            class setupUnit {};
            class tablet {};
            class hud {};
            class notify {};
            class startRound {};
            class spawnBloons {};
            class bloonLocal {};
            class popLocal {};
            class clientTick {};
            class onFiredMan {};
            class damageBloon {};
            class serverTick {};
            class towerFire {};
            class requestBuild {};
            class createTower {};
            class towerCoverage {};
            class towerActions {};
            class requestUpgrade {};
            class requestSell {};
            class manTower {};
            class moveInGunnerLocal {};
            class remanTower {};
            class syncJIP {};
            class gameOver {};
        };
    };
};
