// GENERATED by tools/gen.py from sheets/ui.json
class CfgMainMenuSpotlight {
    class BloonsOps_Solo {
        text = "Bloons Ops: pop 20 rounds of bloons on Altis. Co-op: Multiplayer > Host.";
        textIsQuote = 0;
        picture = "\z\bloonsops\addons\main\ui\spotlight_co.paa";
        action = "playMission ['', configFile >> 'CfgMissions' >> 'Missions' >> 'BloonsOps_Altis']";
        actionText = "Play Bloons Ops";
        condition = "true";
    };
};
