// GENERATED by tools/gen.py from sheets/*.json - edit the sheets, not this file.

BO_Bloons = createHashMap;
BO_Bloons set ["red", createHashMapFromArray [["id","red"],["name","Red Bloon"],["rgba",[0.85,0.05,0.05,1]],["speed_mps",6.0],["child",""],["child_count",0],["lives_cost",1],["pop_cash",1],["needs_lead_popper",false],["camo",false]]];
BO_Bloons set ["blue", createHashMapFromArray [["id","blue"],["name","Blue Bloon"],["rgba",[0.1,0.45,0.95,1]],["speed_mps",8.4],["child","red"],["child_count",1],["lives_cost",2],["pop_cash",1],["needs_lead_popper",false],["camo",false]]];
BO_Bloons set ["green", createHashMapFromArray [["id","green"],["name","Green Bloon"],["rgba",[0.2,0.8,0.1,1]],["speed_mps",10.8],["child","blue"],["child_count",1],["lives_cost",3],["pop_cash",1],["needs_lead_popper",false],["camo",false]]];
BO_Bloons set ["yellow", createHashMapFromArray [["id","yellow"],["name","Yellow Bloon"],["rgba",[1.0,0.9,0.05,1]],["speed_mps",19.2],["child","green"],["child_count",1],["lives_cost",4],["pop_cash",1],["needs_lead_popper",false],["camo",false]]];
BO_Bloons set ["pink", createHashMapFromArray [["id","pink"],["name","Pink Bloon"],["rgba",[1.0,0.45,0.7,1]],["speed_mps",21.0],["child","yellow"],["child_count",1],["lives_cost",5],["pop_cash",1],["needs_lead_popper",false],["camo",false]]];
BO_Bloons set ["lead", createHashMapFromArray [["id","lead"],["name","Lead Bloon"],["rgba",[0.45,0.47,0.5,1]],["speed_mps",6.0],["child","pink"],["child_count",2],["lives_cost",11],["pop_cash",1],["needs_lead_popper",true],["camo",false]]];
BO_Bloons set ["camo_green", createHashMapFromArray [["id","camo_green"],["name","Camo Green Bloon"],["rgba",[0.33,0.42,0.22,0.85]],["speed_mps",10.8],["child","blue"],["child_count",1],["lives_cost",3],["pop_cash",1],["needs_lead_popper",false],["camo",true]]];

BO_Towers = createHashMap;
BO_Towers set ["dart_squad", createHashMapFromArray [["id","dart_squad"],["name","Dart Squad"],["cost",200],["kind","infantry"],["object_class","B_Soldier_F"],["crew_class","B_Soldier_F"],["crew_count",3],["range_m",25],["fire_interval_s",1.2],["damage",1],["pierce",1],["splash_m",0],["impact_delay_s",0],["impact_ammo",""],["pops_lead",false],["sees_camo",false],["mannable",false],["upgrade","veteran_squad"],["blurb","Three riflemen. Cheap, steady, short range."]]];
BO_Towers set ["hmg_nest", createHashMapFromArray [["id","hmg_nest"],["name","M2 HMG Nest"],["cost",450],["kind","static"],["object_class","B_HMG_01_high_F"],["crew_class","B_Soldier_F"],["crew_count",1],["range_m",40],["fire_interval_s",0.25],["damage",1],["pierce",1],["splash_m",0],["impact_delay_s",0],["impact_ammo",""],["pops_lead",false],["sees_camo",false],["mannable",true],["upgrade","ap_rounds"],["blurb","Fast .50 cal. Hop on the gun yourself."]]];
BO_Towers set ["sniper", createHashMapFromArray [["id","sniper"],["name","Sniper"],["cost",350],["kind","infantry"],["object_class","B_sniper_F"],["crew_class","B_sniper_F"],["crew_count",1],["range_m",400],["fire_interval_s",2.0],["damage",2],["pierce",1],["splash_m",0],["impact_delay_s",0],["impact_ammo",""],["pops_lead",false],["sees_camo",true],["mannable",false],["upgrade","rapid_bolt"],["blurb","Sees camo bloons. Hits anywhere on the track."]]];
BO_Towers set ["mortar", createHashMapFromArray [["id","mortar"],["name","Mk6 Mortar"],["cost",750],["kind","static"],["object_class","B_Mortar_01_F"],["crew_class","B_Soldier_F"],["crew_count",1],["range_m",300],["fire_interval_s",4.0],["damage",1],["pierce",25],["splash_m",6],["impact_delay_s",2.0],["impact_ammo","Sh_82mm_AMOS"],["pops_lead",true],["sees_camo",false],["mannable",false],["upgrade","heavy_shells"],["blurb","Explosive splash. Pops lead. Danger close!"]]];

BO_Upgrades = createHashMap;
BO_Upgrades set ["veteran_squad", createHashMapFromArray [["id","veteran_squad"],["tower","dart_squad"],["name","Veteran Squad"],["cost",220],["range_mult",1.2],["interval_mult",0.7],["damage_add",0],["pierce_add",1],["splash_add",0],["grants_lead",false],["grants_camo",false],["blurb","Faster, longer reach, each shot pops 2."]]];
BO_Upgrades set ["ap_rounds", createHashMapFromArray [["id","ap_rounds"],["tower","hmg_nest"],["name","AP Rounds"],["cost",350],["range_mult",1.0],["interval_mult",1.0],["damage_add",1],["pierce_add",0],["splash_add",0],["grants_lead",true],["grants_camo",false],["blurb","Armour piercing: 2 layers per hit and pops lead."]]];
BO_Upgrades set ["rapid_bolt", createHashMapFromArray [["id","rapid_bolt"],["tower","sniper"],["name","Semi-Auto Rifle"],["cost",300],["range_mult",1.0],["interval_mult",0.5],["damage_add",0],["pierce_add",0],["splash_add",0],["grants_lead",false],["grants_camo",false],["blurb","Fires twice as fast."]]];
BO_Upgrades set ["heavy_shells", createHashMapFromArray [["id","heavy_shells"],["tower","mortar"],["name","Heavy Shells"],["cost",400],["range_mult",1.0],["interval_mult",1.0],["damage_add",1],["pierce_add",15],["splash_add",4],["grants_lead",false],["grants_camo",false],["blurb","Bigger blast, 2 layers per hit."]]];

BO_Maps = createHashMap;
BO_Maps set ["altis_airfield", createHashMapFromArray [["id","altis_airfield"],["world","Altis"],["mission_dir","BloonsOps.Altis"],["search_center",[14100,16300]],["search_radius_m",600],["fallback_dir_deg",60]]];

BO_Sounds = createHashMap;
BO_Sounds set ["pop", createHashMapFromArray [["id","pop"],["file","sounds\pop.ogg"],["freq_hz",900],["length_s",0.12],["volume",2.0],["range_m",150]]];
BO_Sounds set ["build", createHashMapFromArray [["id","build"],["file","sounds\build.ogg"],["freq_hz",220],["length_s",0.35],["volume",1.5],["range_m",60]]];
BO_Sounds set ["leak", createHashMapFromArray [["id","leak"],["file","sounds\leak.ogg"],["freq_hz",140],["length_s",0.5],["volume",1.0],["range_m",50]]];

BO_Rounds = [];
BO_Rounds pushBack createHashMapFromArray [["id",1],["groups",[["red",20,1.0,0]]],["tip","Bloons follow the cones. Build towers beside the road!"]];
BO_Rounds pushBack createHashMapFromArray [["id",2],["groups",[["red",35,0.7,0]]],["tip",""]];
BO_Rounds pushBack createHashMapFromArray [["id",3],["groups",[["red",25,0.7,0],["blue",5,1.0,2]]],["tip","Blue bloons are faster and hide a red inside."]];
BO_Rounds pushBack createHashMapFromArray [["id",4],["groups",[["red",35,0.5,0],["blue",18,0.8,1]]],["tip",""]];
BO_Rounds pushBack createHashMapFromArray [["id",5],["groups",[["red",5,0.8,0],["blue",27,0.6,1]]],["tip",""]];
BO_Rounds pushBack createHashMapFromArray [["id",6],["groups",[["red",15,0.6,0],["blue",15,0.6,1],["green",4,1.0,1]]],["tip","Green bloons! Consider an M2 HMG Nest."]];
BO_Rounds pushBack createHashMapFromArray [["id",7],["groups",[["red",20,0.5,0],["blue",20,0.5,1],["green",5,1.0,1]]],["tip",""]];
BO_Rounds pushBack createHashMapFromArray [["id",8],["groups",[["red",10,0.5,0],["blue",20,0.5,1],["green",14,0.7,1]]],["tip",""]];
BO_Rounds pushBack createHashMapFromArray [["id",9],["groups",[["green",30,0.6,0]]],["tip",""]];
BO_Rounds pushBack createHashMapFromArray [["id",10],["groups",[["blue",60,0.3,0]]],["tip","Blue swarm incoming!"]];
BO_Rounds pushBack createHashMapFromArray [["id",11],["groups",[["red",10,0.5,0],["blue",10,0.5,0],["green",12,0.6,1],["yellow",3,1.5,1]]],["tip","Yellow bloons are very fast."]];
BO_Rounds pushBack createHashMapFromArray [["id",12],["groups",[["blue",15,0.5,0],["green",10,0.6,1],["yellow",5,1.2,1]]],["tip",""]];
BO_Rounds pushBack createHashMapFromArray [["id",13],["groups",[["blue",50,0.3,0],["green",23,0.5,1]]],["tip",""]];
BO_Rounds pushBack createHashMapFromArray [["id",14],["groups",[["red",40,0.3,0],["blue",20,0.4,0],["green",10,0.5,1],["yellow",9,0.9,1]]],["tip",""]];
BO_Rounds pushBack createHashMapFromArray [["id",15],["groups",[["red",20,0.4,0],["green",15,0.5,1],["yellow",10,0.8,1],["pink",3,1.5,1]]],["tip","Pink bloons: the fastest of all."]];
BO_Rounds pushBack createHashMapFromArray [["id",16],["groups",[["green",20,0.4,0],["yellow",8,0.8,1]]],["tip",""]];
BO_Rounds pushBack createHashMapFromArray [["id",17],["groups",[["yellow",12,0.7,0]]],["tip",""]];
BO_Rounds pushBack createHashMapFromArray [["id",18],["groups",[["green",80,0.2,0]]],["tip","Lead bloons next round: only the Mk6 Mortar or AP Rounds pop them."]];
BO_Rounds pushBack createHashMapFromArray [["id",19],["groups",[["green",10,0.5,0],["yellow",4,0.8,1],["pink",5,0.8,1],["lead",4,2.0,1]]],["tip","LEAD! Explosives only."]];
BO_Rounds pushBack createHashMapFromArray [["id",20],["groups",[["pink",6,0.8,0],["lead",6,1.5,1],["camo_green",6,1.2,1]]],["tip","Camo bloons! Only the Sniper (or your own eyes) can see them."]];

BO_Cfg = createHashMap;
BO_Cfg set ["start_cash", 650];
BO_Cfg set ["start_lives", 100];
BO_Cfg set ["round_bonus_base", 100];
BO_Cfg set ["sell_ratio", 0.7];
BO_Cfg set ["max_players", 4];
BO_Cfg set ["build_distance", 4];
BO_Cfg set ["track_clearance", 5];
BO_Cfg set ["tower_spacing", 3];
BO_Cfg set ["server_tick_s", 0.1];
BO_Cfg set ["bloon_height_m", 1.6];
BO_Cfg set ["track_target_m", 900];
BO_Cfg set ["track_min_m", 400];
BO_Cfg set ["player_hit_radius_m", 0.9];
BO_Cfg set ["final_round", 20];
BO_TowerOrder = ["dart_squad","hmg_nest","sniper","mortar"];
