// GENERATED by tools/gen_oa.py from sheets/*.json - edit the sheets, not this file.
// Each sheet row is an array; these macros name its fields and its rows.
#define B_ID 0
#define B_NAME 1
#define B_RGBA 2
#define B_PATTERN 3
#define B_SPEED_MPS 4
#define B_CHILD 5
#define B_CHILD_COUNT 6
#define B_LIVES_COST 7
#define B_POP_CASH 8
#define B_NEEDS_LEAD_POPPER 9
#define B_CAMO 10
#define BROW_RED 0
#define BROW_BLUE 1
#define BROW_GREEN 2
#define BROW_YELLOW 3
#define BROW_PINK 4
#define BROW_LEAD 5
#define BROW_CAMO_GREEN 6
#define T_ID 0
#define T_NAME 1
#define T_SECTION 2
#define T_COST 3
#define T_KIND 4
#define T_OBJECT_CLASS 5
#define T_CREW_CLASS 6
#define T_CREW_COUNT 7
#define T_HOVER_M 8
#define T_RANGE_M 9
#define T_FIRE_INTERVAL_S 10
#define T_DAMAGE 11
#define T_PIERCE 12
#define T_AOE 13
#define T_SPLASH_M 14
#define T_IMPACT_DELAY_S 15
#define T_IMPACT_AMMO 16
#define T_SLOW_MULT 17
#define T_SLOW_S 18
#define T_INCOME 19
#define T_POPS_LEAD 20
#define T_SEES_CAMO 21
#define T_MANNABLE 22
#define T_BODY_RGBA 23
#define T_ACCENT_RGBA 24
#define T_FX_RGBA 25
#define T_OA_NAME 26
#define T_OA_OBJECT_CLASS 27
#define T_OA_CREW_CLASS 28
#define T_OA_TURRETS 29
#define T_UPGRADE 30
#define T_BLURB 31
#define TROW_DART_SQUAD 0
#define TROW_HMG_NEST 1
#define TROW_SNIPER 2
#define TROW_MORTAR 3
#define TROW_GHOST_HAWK 4
#define TROW_BLACKFOOT 5
#define TROW_DART_MONKEY 6
#define TROW_BOOMERANG 7
#define TROW_BOMB_SHOOTER 8
#define TROW_TACK_SHOOTER 9
#define TROW_ICE_MONKEY 10
#define TROW_GLUE_GUNNER 11
#define TROW_NINJA_MONKEY 12
#define TROW_SUPER_MONKEY 13
#define TROW_BANANA_FARM 14
#define U_ID 0
#define U_TOWER 1
#define U_NAME 2
#define U_COST 3
#define U_RANGE_MULT 4
#define U_INTERVAL_MULT 5
#define U_DAMAGE_ADD 6
#define U_PIERCE_ADD 7
#define U_SPLASH_ADD 8
#define U_GRANTS_LEAD 9
#define U_GRANTS_CAMO 10
#define U_INCOME_ADD 11
#define U_BLURB 12
#define UROW_VETERAN_SQUAD 0
#define UROW_AP_ROUNDS 1
#define UROW_RAPID_BOLT 2
#define UROW_HEAVY_SHELLS 3
#define UROW_MINIGUN_DOORS 4
#define UROW_HELLFIRE_VOLLEY 5
#define UROW_RAZOR_DARTS 6
#define UROW_GLAIVES 7
#define UROW_BIGGER_BOMBS 8
#define UROW_FASTER_TACKS 9
#define UROW_ARCTIC_WIND 10
#define UROW_CORROSIVE_GLUE 11
#define UROW_SHARP_SHURIKENS 12
#define UROW_LASER_BLASTS 13
#define UROW_BIGGER_BUNCHES 14
#define R_ID 0
#define R_GROUPS 1
#define R_TIP 2
#define S_ID 0
#define S_FILE 1
#define S_FREQ_HZ 2
#define S_LENGTH_S 3
#define S_VOLUME 4
#define S_RANGE_M 5
#define SROW_POP 0
#define SROW_BUILD 1
#define SROW_LEAK 2
#define M_ID 0
#define M_EDITION 1
#define M_WORLD 2
#define M_MISSION_DIR 3
#define M_SEARCH_CENTER 4
#define M_SEARCH_RADIUS_M 5
#define M_FALLBACK_DIR_DEG 6
#define MROW_ALTIS_AIRFIELD 0
#define MROW_TAKISTAN_RASMAN 1
#define P_ID 0
#define P_CLASS 1
#define P_USE 2
#define PROW_PLAYER_UNIT 0
#define PROW_TRACK_CONE 1
#define PROW_TRACK_ENTRY 2
#define PROW_SANDBAG 3
#define PROW_HELIPAD 4
#define PROW_BLOON_SPHERE 5
#define PROW_SMALL_SPHERE 6
#define PROW_TINY_SPHERE 7
#define PROW_MORTAR_SHELL 8
#define PROP_PLAYER_UNIT ((BO_OaProps select 0) select P_CLASS)
#define PROP_TRACK_CONE ((BO_OaProps select 1) select P_CLASS)
#define PROP_TRACK_ENTRY ((BO_OaProps select 2) select P_CLASS)
#define PROP_SANDBAG ((BO_OaProps select 3) select P_CLASS)
#define PROP_HELIPAD ((BO_OaProps select 4) select P_CLASS)
#define PROP_BLOON_SPHERE ((BO_OaProps select 5) select P_CLASS)
#define PROP_SMALL_SPHERE ((BO_OaProps select 6) select P_CLASS)
#define PROP_TINY_SPHERE ((BO_OaProps select 7) select P_CLASS)
#define PROP_MORTAR_SHELL ((BO_OaProps select 8) select P_CLASS)
#define CFG_START_CASH (BO_Cfg select 0)
#define CFG_START_LIVES (BO_Cfg select 1)
#define CFG_ROUND_BONUS_BASE (BO_Cfg select 2)
#define CFG_SELL_RATIO (BO_Cfg select 3)
#define CFG_MAX_PLAYERS (BO_Cfg select 4)
#define CFG_BUILD_DISTANCE (BO_Cfg select 5)
#define CFG_TRACK_CLEARANCE (BO_Cfg select 6)
#define CFG_TOWER_SPACING (BO_Cfg select 7)
#define CFG_SERVER_TICK_S (BO_Cfg select 8)
#define CFG_BLOON_HEIGHT_M (BO_Cfg select 9)
#define CFG_TRACK_TARGET_M (BO_Cfg select 10)
#define CFG_TRACK_MIN_M (BO_Cfg select 11)
#define CFG_PLAYER_HIT_RADIUS_M (BO_Cfg select 12)
#define CFG_FINAL_ROUND (BO_Cfg select 13)
#define CFG_FLATTEN_RADIUS_M (BO_Cfg select 14)
#define CFG_FLATTEN_KEEP (BO_Cfg select 15)
#define CFG_FLATTEN_MAX_DEV_M (BO_Cfg select 16)
#define CFG_FLATTEN_WINDOW_M (BO_Cfg select 17)
#define CFG_PLAYERS_INVINCIBLE (BO_Cfg select 18)
#define CFG_PLAYER_SPEED_MULT (BO_Cfg select 19)
#define T_BODY_TEX 32
#define T_ACCENT_TEX 33
#define BO_PATH(f) ("\z\bloonsops_oa\addons\main\" + f)
