// GENERATED by tools/gen_oa.py from sheets/sounds.json (OA plays 3D sounds with say3D)
class CfgSounds {
    sounds[] = {};
    class bo_pop { name = "bo_pop"; sound[] = {"\z\bloonsops_oa\addons\main\sounds\pop.ogg", 2.0, 1}; titles[] = {}; };
    class bo_build { name = "bo_build"; sound[] = {"\z\bloonsops_oa\addons\main\sounds\build.ogg", 1.5, 1}; titles[] = {}; };
    class bo_leak { name = "bo_leak"; sound[] = {"\z\bloonsops_oa\addons\main\sounds\leak.ogg", 1.0, 1}; titles[] = {}; };
};
