// GENERATED by tools/gen_oa.py from sheets/towers.json
class BO_TabletDialog {
    idd = 77200;
    movingEnable = 0;
    class controlsBackground {
        class Bg: BO_RscText { idc = -1; x = 0.08; y = 0.06; w = 0.84; h = 0.88; colorBackground[] = {0.05, 0.07, 0.05, 0.93}; text = ""; };
    };
    class controls {
        class Title: BO_RscText { idc = 77201; x = 0.1; y = 0.08; w = 0.8; h = 0.06; sizeEx = 0.05; text = "BUILD TABLET"; colorText[] = {1, 0.85, 0, 1}; };
        class HeadArma: BO_RscText { idc = -1; x = 0.1; y = 0.16; w = 0.38; h = 0.05; text = "ARMA 2: OA"; colorText[] = {0.72, 0.88, 0.48, 1}; };
        class HeadBtd: BO_RscText { idc = -1; x = 0.52; y = 0.16; w = 0.38; h = 0.05; text = "BLOONS TD"; colorText[] = {1, 0.78, 0.25, 1}; };
        class Btn0: BO_RscButton { idc = 77300; x = 0.1; y = 0.220; w = 0.38; h = 0.055; text = "Dart Squad   $200"; colorBackground[] = {0.24, 0.32, 0.16, 0.95}; tooltip = "Three riflemen. Cheap, steady, short range."; action = "[0] call BO_fnc_tabletPick"; };
        class Btn1: BO_RscButton { idc = 77301; x = 0.1; y = 0.282; w = 0.38; h = 0.055; text = "M2 HMG Nest   $450"; colorBackground[] = {0.24, 0.32, 0.16, 0.95}; tooltip = "Fast .50 cal. Hop on the gun yourself."; action = "[1] call BO_fnc_tabletPick"; };
        class Btn2: BO_RscButton { idc = 77302; x = 0.1; y = 0.344; w = 0.38; h = 0.055; text = "Sniper Team   $350"; colorBackground[] = {0.24, 0.32, 0.16, 0.95}; tooltip = "Sees camo bloons. Hits anywhere on the track."; action = "[2] call BO_fnc_tabletPick"; };
        class Btn3: BO_RscButton { idc = 77303; x = 0.1; y = 0.406; w = 0.38; h = 0.055; text = "M252 Mortar   $750"; colorBackground[] = {0.24, 0.32, 0.16, 0.95}; tooltip = "Explosive splash. Pops lead."; action = "[3] call BO_fnc_tabletPick"; };
        class Btn4: BO_RscButton { idc = 77304; x = 0.1; y = 0.468; w = 0.38; h = 0.055; text = "UH-60M Black Hawk   $900"; colorBackground[] = {0.24, 0.32, 0.16, 0.95}; tooltip = "Hovers over its pad; two door gunners rake the road."; action = "[4] call BO_fnc_tabletPick"; };
        class Btn5: BO_RscButton { idc = 77305; x = 0.1; y = 0.530; w = 0.38; h = 0.055; text = "AH-64D Apache   $1600"; colorBackground[] = {0.24, 0.32, 0.16, 0.95}; tooltip = "Attack helicopter: thermal sights see camo, rockets pop lead."; action = "[5] call BO_fnc_tabletPick"; };
        class Btn6: BO_RscButton { idc = 77306; x = 0.52; y = 0.220; w = 0.38; h = 0.055; text = "Dart Monkey   $170"; colorBackground[] = {0.7, 0.38, 0.06, 0.95}; tooltip = "The classic. Throws a dart that pops 2 bloons."; action = "[6] call BO_fnc_tabletPick"; };
        class Btn7: BO_RscButton { idc = 77307; x = 0.52; y = 0.282; w = 0.38; h = 0.055; text = "Boomerang Monkey   $275"; colorBackground[] = {0.7, 0.38, 0.06, 0.95}; tooltip = "Boomerang swings through 4 bloons."; action = "[7] call BO_fnc_tabletPick"; };
        class Btn8: BO_RscButton { idc = 77308; x = 0.52; y = 0.344; w = 0.38; h = 0.055; text = "Bomb Shooter   $450"; colorBackground[] = {0.7, 0.38, 0.06, 0.95}; tooltip = "Cannon blasts pop groups, and pop lead."; action = "[8] call BO_fnc_tabletPick"; };
        class Btn9: BO_RscButton { idc = 77309; x = 0.52; y = 0.406; w = 0.38; h = 0.055; text = "Tack Shooter   $260"; colorBackground[] = {0.7, 0.38, 0.06, 0.95}; tooltip = "Sprays tacks at every bloon nearby."; action = "[9] call BO_fnc_tabletPick"; };
        class Btn10: BO_RscButton { idc = 77310; x = 0.52; y = 0.468; w = 0.38; h = 0.055; text = "Ice Monkey   $400"; colorBackground[] = {0.7, 0.38, 0.06, 0.95}; tooltip = "Freezes every bloon nearby for a moment. Can't pop lead."; action = "[10] call BO_fnc_tabletPick"; };
        class Btn11: BO_RscButton { idc = 77311; x = 0.52; y = 0.530; w = 0.38; h = 0.055; text = "Glue Gunner   $225"; colorBackground[] = {0.7, 0.38, 0.06, 0.95}; tooltip = "Glues a bloon so it moves at half speed."; action = "[11] call BO_fnc_tabletPick"; };
        class Btn12: BO_RscButton { idc = 77312; x = 0.52; y = 0.592; w = 0.38; h = 0.055; text = "Ninja Monkey   $400"; colorBackground[] = {0.7, 0.38, 0.06, 0.95}; tooltip = "Fast shurikens, and sees camo bloons."; action = "[12] call BO_fnc_tabletPick"; };
        class Btn13: BO_RscButton { idc = 77313; x = 0.52; y = 0.654; w = 0.38; h = 0.055; text = "Super Monkey   $2500"; colorBackground[] = {0.7, 0.38, 0.06, 0.95}; tooltip = "Throws darts like a machine gun."; action = "[13] call BO_fnc_tabletPick"; };
        class Btn14: BO_RscButton { idc = 77314; x = 0.52; y = 0.716; w = 0.38; h = 0.055; text = "Banana Farm   $1000"; colorBackground[] = {0.7, 0.38, 0.06, 0.95}; tooltip = "Pays $80 at the end of every round."; action = "[14] call BO_fnc_tabletPick"; };
        class Hint: BO_RscText { idc = 77202; x = 0.1; y = 0.86; w = 0.62; h = 0.05; sizeEx = 0.03; text = "Towers appear 4 m in front of you. Stay 5 m off the road."; };
        class Close: BO_RscButton { idc = -1; x = 0.74; y = 0.86; w = 0.16; h = 0.055; text = "Close"; action = "closeDialog 0"; };
    };
};
