// GENERATED by tools/gen_oa.py from sheets/*.json - edit the sheets, not this file.

BO_Bloons = [
  ["red","Red Bloon",[0.85,0.05,0.05,1],"glossy",6.0,-1,0,1,1,false,false],
  ["blue","Blue Bloon",[0.1,0.45,0.95,1],"glossy",8.4,0,1,2,1,false,false],
  ["green","Green Bloon",[0.2,0.8,0.1,1],"glossy",10.8,1,1,3,1,false,false],
  ["yellow","Yellow Bloon",[1.0,0.9,0.05,1],"glossy",19.2,2,1,4,1,false,false],
  ["pink","Pink Bloon",[1.0,0.45,0.7,1],"glossy",21.0,3,1,5,1,false,false],
  ["lead","Lead Bloon",[0.45,0.47,0.5,1],"metal",6.0,4,2,11,1,true,false],
  ["camo_green","Camo Green Bloon",[0.33,0.42,0.22,0.85],"camo",10.8,1,1,3,1,false,true]
];
BO_Towers = [
  ["dart_squad","Dart Squad","arma",200,"infantry","B_Soldier_F","B_Soldier_F",3,0,25,1.2,1,1,false,0,0,"",1,0,0,false,false,false,[0.45,0.28,0.12,1],[0.45,0.28,0.12,1],[1,0.9,0.4,1],"Dart Squad","US_Soldier_EP1","US_Soldier_EP1",[],0,"Three riflemen. Cheap, steady, short range.","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa"],
  ["hmg_nest","M2 HMG Nest","arma",450,"static","B_HMG_01_high_F","B_Soldier_F",1,0,40,0.25,1,1,false,0,0,"",1,0,0,false,false,true,[0.45,0.28,0.12,1],[0.45,0.28,0.12,1],[1,0.8,0.3,1],"M2 HMG Nest","M2StaticMG_US_EP1","US_Soldier_EP1",[[0]],1,"Fast .50 cal. Hop on the gun yourself.","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa"],
  ["sniper","Sniper Team","arma",350,"infantry","B_sniper_F","B_sniper_F",1,0,400,2.0,2,1,false,0,0,"",1,0,0,false,true,false,[0.45,0.28,0.12,1],[0.45,0.28,0.12,1],[1,1,1,1],"Sniper Team","US_Soldier_Sniper_EP1","US_Soldier_Sniper_EP1",[],2,"Sees camo bloons. Hits anywhere on the track.","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa"],
  ["mortar","Mk6 Mortar","arma",750,"static","B_Mortar_01_F","B_Soldier_F",1,0,300,4.0,1,25,false,6,2.0,"Sh_82mm_AMOS",1,0,0,true,false,false,[0.45,0.28,0.12,1],[0.45,0.28,0.12,1],[1,0.5,0.1,1],"M252 Mortar","M252_US_EP1","US_Soldier_EP1",[[0]],3,"Explosive splash. Pops lead.","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa"],
  ["ghost_hawk","UH-80 Ghost Hawk","arma",900,"heli","B_Heli_Transport_01_F","",0,25,45,0.3,1,2,false,0,0,"",1,0,0,false,false,false,[0.45,0.28,0.12,1],[0.45,0.28,0.12,1],[1,0.75,0.2,1],"UH-60M Black Hawk","UH60M_EP1","US_Soldier_Pilot_EP1",[[0],[1]],4,"Hovers over its pad; two door gunners rake the road.","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa"],
  ["blackfoot","AH-99 Blackfoot","arma",1600,"heli","B_Heli_Attack_01_dynamicLoadout_F","",0,30,70,1.2,1,12,false,5,0.5,"",1,0,0,true,true,false,[0.45,0.28,0.12,1],[0.45,0.28,0.12,1],[1,0.3,0.1,1],"AH-64D Apache","AH64D_EP1","US_Soldier_Pilot_EP1",[[0]],5,"Attack helicopter: thermal sights see camo, rockets pop lead.","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa"],
  ["dart_monkey","Dart Monkey","btd",170,"monkey","","",0,0,22,0.95,1,2,false,0,0,"",1,0,0,false,false,false,[0.45,0.28,0.12,1],[0.85,0.1,0.1,1],[0.9,0.9,0.9,1],"Dart Monkey","","",[],6,"The classic. Throws a dart that pops 2 bloons.","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa","\z\bloonsops_oa\addons\main\data\c_d91a1a_co.paa"],
  ["boomerang","Boomerang Monkey","btd",275,"monkey","","",0,0,25,1.2,1,4,false,0,0,"",1,0,0,false,false,false,[0.45,0.28,0.12,1],[0.2,0.5,0.9,1],[0.95,0.75,0.3,1],"Boomerang Monkey","","",[],7,"Boomerang swings through 4 bloons.","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa","\z\bloonsops_oa\addons\main\data\c_3380e6_co.paa"],
  ["bomb_shooter","Bomb Shooter","btd",450,"monkey","","",0,0,25,1.5,1,14,false,4,0.3,"",1,0,0,true,false,false,[0.15,0.15,0.15,1],[0.9,0.6,0.1,1],[1,0.55,0,1],"Bomb Shooter","","",[],8,"Cannon blasts pop groups, and pop lead.","\z\bloonsops_oa\addons\main\data\c_262626_co.paa","\z\bloonsops_oa\addons\main\data\c_e6991a_co.paa"],
  ["tack_shooter","Tack Shooter","btd",260,"monkey","","",0,0,14,1.3,1,8,true,0,0,"",1,0,0,false,false,false,[0.9,0.4,0.6,1],[0.8,0.8,0.8,1],[0.95,0.95,0.95,1],"Tack Shooter","","",[],9,"Sprays tacks at every bloon nearby.","\z\bloonsops_oa\addons\main\data\c_e66699_co.paa","\z\bloonsops_oa\addons\main\data\c_cccccc_co.paa"],
  ["ice_monkey","Ice Monkey","btd",400,"monkey","","",0,0,12,2.0,1,20,true,0,0,"",0,1.2,0,false,false,false,[0.6,0.85,1,1],[1,1,1,1],[0.6,0.95,1,1],"Ice Monkey","","",[],10,"Freezes every bloon nearby for a moment. Can't pop lead.","\z\bloonsops_oa\addons\main\data\c_99d9ff_co.paa","\z\bloonsops_oa\addons\main\data\c_ffffff_co.paa"],
  ["glue_gunner","Glue Gunner","btd",225,"monkey","","",0,0,28,1.0,0,1,false,0,0,"",0.5,6,0,false,false,false,[0.45,0.28,0.12,1],[0.95,0.85,0.1,1],[0.95,0.9,0.2,1],"Glue Gunner","","",[],11,"Glues a bloon so it moves at half speed.","\z\bloonsops_oa\addons\main\data\c_73471f_co.paa","\z\bloonsops_oa\addons\main\data\c_f2d91a_co.paa"],
  ["ninja_monkey","Ninja Monkey","btd",400,"monkey","","",0,0,26,0.6,1,2,false,0,0,"",1,0,0,false,true,false,[0.12,0.12,0.12,1],[0.85,0.05,0.05,1],[0.8,0.8,0.85,1],"Ninja Monkey","","",[],12,"Fast shurikens, and sees camo bloons.","\z\bloonsops_oa\addons\main\data\c_1f1f1f_co.paa","\z\bloonsops_oa\addons\main\data\c_d90d0d_co.paa"],
  ["super_monkey","Super Monkey","btd",2500,"monkey","","",0,0,45,0.08,1,1,false,0,0,"",1,0,0,false,false,false,[0.15,0.35,0.9,1],[0.9,0.1,0.1,1],[1,1,0.5,1],"Super Monkey","","",[],13,"Throws darts like a machine gun.","\z\bloonsops_oa\addons\main\data\c_2659e6_co.paa","\z\bloonsops_oa\addons\main\data\c_e61a1a_co.paa"],
  ["banana_farm","Banana Farm","btd",1000,"farm","","",0,0,0,1,0,0,false,0,0,"",1,0,80,false,false,false,[0.45,0.7,0.2,1],[1,0.9,0.15,1],[1,0.9,0.15,1],"Banana Farm","","",[],14,"Pays $80 at the end of every round.","\z\bloonsops_oa\addons\main\data\c_73b233_co.paa","\z\bloonsops_oa\addons\main\data\c_ffe626_co.paa"]
];
BO_Upgrades = [
  ["veteran_squad",0,"Veteran Squad",220,1.2,0.7,0,1,0,false,false,0,"Faster, longer reach, each shot pops 2."],
  ["ap_rounds",1,"AP Rounds",350,1.0,1.0,1,0,0,true,false,0,"Armour piercing: 2 layers per hit and pops lead."],
  ["rapid_bolt",2,"Semi-Auto Rifle",300,1.0,0.5,0,0,0,false,false,0,"Fires twice as fast."],
  ["heavy_shells",3,"Heavy Shells",400,1.0,1.0,1,15,4,false,false,0,"Bigger blast, 2 layers per hit."],
  ["minigun_doors",4,"Miniguns",600,1.0,0.5,0,1,0,false,false,0,"Door miniguns: twice the fire rate."],
  ["hellfire_volley",5,"Rocket Volley",1200,1.0,1.0,1,0,3,false,false,0,"Bigger rocket salvos, 2 layers per hit."],
  ["razor_darts",6,"Razor Sharp Shots",140,1.0,1.0,0,2,0,false,false,0,"Darts pop 4 bloons."],
  ["glaives",7,"Glaives",250,1.0,1.0,0,3,0,false,false,0,"Glaives slice through 7 bloons."],
  ["bigger_bombs",8,"Bigger Bombs",350,1.0,1.0,1,0,2,false,false,0,"Bigger blasts, 2 layers per hit."],
  ["faster_tacks",9,"Faster Shooting",210,1.0,0.6,0,0,0,false,false,0,"Sprays tacks much faster."],
  ["arctic_wind",10,"Arctic Wind",300,1.6,1.0,0,0,0,false,false,0,"Freezes bloons in a much wider area."],
  ["corrosive_glue",11,"Corrosive Glue",300,1.0,1.0,1,0,0,false,false,0,"The glue also pops a layer."],
  ["sharp_shurikens",12,"Sharp Shurikens",300,1.0,1.0,0,2,0,false,false,0,"Each shuriken pops 4 bloons."],
  ["laser_blasts",13,"Laser Blasts",2300,1.0,1.0,1,1,0,false,false,0,"Lasers: 2 layers and 2 bloons per shot."],
  ["bigger_bunches",14,"Bigger Bunches",550,1.0,1.0,0,0,0,false,false,40,"+$40 per round."]
];
BO_Rounds = [
  [1,[[0,20,1.0,0]],"Bloons follow the cones. Build towers beside the road!"],
  [2,[[0,35,0.7,0]],""],
  [3,[[0,25,0.7,0],[1,5,1.0,2]],"Blue bloons are faster and hide a red inside."],
  [4,[[0,35,0.5,0],[1,18,0.8,1]],""],
  [5,[[0,5,0.8,0],[1,27,0.6,1]],""],
  [6,[[0,15,0.6,0],[1,15,0.6,1],[2,4,1.0,1]],"Green bloons! Consider an M2 HMG Nest."],
  [7,[[0,20,0.5,0],[1,20,0.5,1],[2,5,1.0,1]],""],
  [8,[[0,10,0.5,0],[1,20,0.5,1],[2,14,0.7,1]],""],
  [9,[[2,30,0.6,0]],""],
  [10,[[1,60,0.3,0]],"Blue swarm incoming!"],
  [11,[[0,10,0.5,0],[1,10,0.5,0],[2,12,0.6,1],[3,3,1.5,1]],"Yellow bloons are very fast."],
  [12,[[1,15,0.5,0],[2,10,0.6,1],[3,5,1.2,1]],""],
  [13,[[1,50,0.3,0],[2,23,0.5,1]],""],
  [14,[[0,40,0.3,0],[1,20,0.4,0],[2,10,0.5,1],[3,9,0.9,1]],""],
  [15,[[0,20,0.4,0],[2,15,0.5,1],[3,10,0.8,1],[4,3,1.5,1]],"Pink bloons: the fastest of all."],
  [16,[[2,20,0.4,0],[3,8,0.8,1]],""],
  [17,[[3,12,0.7,0]],""],
  [18,[[2,80,0.2,0]],"Lead bloons next round: only the Mk6 Mortar or AP Rounds pop them."],
  [19,[[2,10,0.5,0],[3,4,0.8,1],[4,5,0.8,1],[5,4,2.0,1]],"LEAD! Explosives only."],
  [20,[[4,6,0.8,0],[5,6,1.5,1],[6,6,1.2,1]],"Camo bloons! Only the Sniper (or your own eyes) can see them."]
];
BO_Sounds = [
  ["pop","sounds\pop.ogg",900,0.12,2.0,150],
  ["build","sounds\build.ogg",220,0.35,1.5,60],
  ["leak","sounds\leak.ogg",140,0.5,1.0,50]
];
BO_Maps = [
  ["altis_airfield","a3","Altis","BloonsOps.Altis",[14100,16300],600,60],
  ["takistan_rasman","oa","Takistan","BloonsOps.Takistan",[6000,11200],700,90]
];
BO_OaProps = [
  ["player_unit","US_Soldier_EP1","playable slots in mission.sqm"],
  ["track_cone","RoadCone","cones lining the track"],
  ["track_entry","Sign_arrow_down_large_EP1","marks where bloons enter"],
  ["sandbag","Land_fort_bagfence_round","infantry tower anchor"],
  ["helipad","HeliH","helicopter tower pad"],
  ["bloon_sphere","Sign_sphere100cm_EP1","bloon body (until BTD6 billboards)"],
  ["small_sphere","Sign_sphere25cm_EP1","bloon knot, monkey parts"],
  ["tiny_sphere","Sign_sphere10cm_EP1","monkey eyes"],
  ["mortar_shell","Sh_81_HE","real mortar impact (players invincible)"]
];
BO_Cfg = [650,100,100,0.7,4,4,5,3,0.1,1.6,900,400,0.9,20,80,0.25,2.5,150,true,2.5];
BO_TexTan = "\z\bloonsops_oa\addons\main\data\c_f2c78c_co.paa";
BO_TexWhite = "\z\bloonsops_oa\addons\main\data\c_ffffff_co.paa";
BO_NetAllowed = ["BO_fnc_notify","BO_fnc_startRound","BO_fnc_rebaseLocal","BO_fnc_bloonLocal","BO_fnc_popLocal","BO_fnc_damageBloon","BO_fnc_requestBuild","BO_fnc_towerLocal","BO_fnc_requestUpgrade","BO_fnc_requestSell","BO_fnc_manTower","BO_fnc_moveInGunnerLocal","BO_fnc_syncJIP","BO_fnc_endLocal"];
