name = "Bloons Ops"
author = "Bloons Ops contributors"
prefix = "bloonsops"
mainprefix = "z"

[version]
major = 0
minor = 1
patch = 0
git_hash = 0

[files]
include = ["mod.cpp", "README.md"]

[hemtt.release]
folder = "bloonsops"
