#!/usr/bin/env python3
"""Bloons TD Ops generator. The sheets in sheets/*.json are the source of truth.

  python3 tools/gen.py preflight   # lay every sheet over the others: unfilled cells, bad types, dangling refs
  python3 tools/gen.py gen         # preflight, then write the generated SQF/config files
  python3 tools/gen.py verify      # list cells still waiting on a check in the running game
"""
import json, os, re, sys, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEETS = ["bloons", "towers", "upgrades", "rounds", "constants", "btd6_art", "sounds", "maps", "hooks"]
MAIN = os.path.join(ROOT, "addons", "main")
MISSIONS = os.path.join(ROOT, "addons", "missions")
PREFIX = r"z\btdops\addons"
GEN_NOTE = "// GENERATED by tools/gen.py from sheets/*.json - edit the sheets, not this file.\n"


def load():
    return {s: json.load(open(os.path.join(ROOT, "sheets", s + ".json"))) for s in SHEETS}


def ids(sh):
    return {r["id"] for r in sh["rows"]}


# ---------------------------------------------------------------- preflight
def check_cell(errs, where, typ, v, S):
    opt = typ.endswith("?")
    t = typ.rstrip("?")
    if v is None:
        errs.append(f"{where}: unfilled"); return
    if t == "string":
        if not isinstance(v, str) or (v == "" and not opt): errs.append(f"{where}: needs text")
    elif t == "int":
        if not isinstance(v, int) or isinstance(v, bool): errs.append(f"{where}: needs a whole number, got {v!r}")
    elif t == "number":
        if not isinstance(v, (int, float)) or isinstance(v, bool): errs.append(f"{where}: needs a number, got {v!r}")
    elif t == "bool":
        if not isinstance(v, bool): errs.append(f"{where}: needs true/false")
    elif t == "rgb":
        if not (isinstance(v, list) and len(v) == 3 and all(isinstance(x, (int, float)) and 0 <= x <= 1 for x in v)):
            errs.append(f"{where}: needs [r,g,b] in 0..1")
    elif t == "xy":
        if not (isinstance(v, list) and len(v) == 2 and all(isinstance(x, (int, float)) for x in v)): errs.append(f"{where}: needs [x,y]")
    elif t == "xy[]":
        if not (isinstance(v, list) and len(v) >= 2): errs.append(f"{where}: needs at least 2 points")
        else:
            for i, p in enumerate(v): check_cell(errs, f"{where}[{i}]", "xy", p, S)
    elif t == "string[]":
        if not (isinstance(v, list) and all(isinstance(x, str) and x for x in v)): errs.append(f"{where}: needs a list of text")
    elif t.startswith("enum:"):
        if v not in t[5:].split("|"): errs.append(f"{where}: {v!r} is not one of {t[5:]}")
    elif t.startswith("ref[]:"):
        target = t[6:]
        if not isinstance(v, list): errs.append(f"{where}: needs a list of {target} ids"); return
        for x in v:
            if x not in ids(S[target]): errs.append(f"{where}: {x!r} is not a row of {target}")
    elif t.startswith("ref:"):
        target = t[4:]
        if v not in ids(S[target]): errs.append(f"{where}: {v!r} is not a row of {target}")
    elif t == "group[]":
        if not isinstance(v, list) or not v: errs.append(f"{where}: needs groups"); return
        for i, g in enumerate(v):
            ok = isinstance(g, list) and len(g) == 4 and g[0] in ids(S["bloons"]) and isinstance(g[1], int) and g[1] > 0 \
                and isinstance(g[2], (int, float)) and g[2] >= 0 and isinstance(g[3], (int, float)) and g[3] >= 0
            if not ok: errs.append(f"{where}[{i}]: needs [bloon id, count>0, spacing_s, start_s], got {g!r}")
    elif t == "number|bool|string":
        if v == "" : errs.append(f"{where}: unfilled")
    else:
        errs.append(f"{where}: unknown column type {typ}")


def preflight(S, quiet=False):
    errs = []
    cells = 0
    for name, sh in S.items():
        cols = sh["columns"]
        seen = set()
        for i, row in enumerate(sh["rows"]):
            rid = row.get("id", f"#{i}")
            if rid in seen: errs.append(f"{name}.{rid}: duplicate id")
            seen.add(rid)
            for k in row:
                if k not in cols: errs.append(f"{name}.{rid}.{k}: column not declared")
            for c, typ in cols.items():
                cells += 1
                check_cell(errs, f"{name}.{rid}.{c}", typ, row.get(c), S)
    # cross-sheet rules
    T = {r["id"]: r for r in S["towers"]["rows"]}
    for u in S["upgrades"]["rows"]:
        if u["tower"] in T and T[u["tower"]]["upgrade"] != u["id"]:
            errs.append(f"upgrades.{u['id']}.tower: tower {u['tower']} names upgrade {T[u['tower']]['upgrade']!r}, not this row")
    for t in T.values():
        if t["section"] == "BTD6" and t["art"] == "none": errs.append(f"towers.{t['id']}.art: a BTD6 tower needs a picture")
        if t["section"] == "BTD6" and t["billboard_m"] <= 0: errs.append(f"towers.{t['id']}.billboard_m: a BTD6 tower needs a size")
        if t["section"] == "ARMA" and t["object_class"] == "none" and t["crew_class"] == "none":
            errs.append(f"towers.{t['id']}: an ARMA tower needs an object_class or a crew_class")
        if t["section"] == "BTD6" and t["fire_sound"] == "none": errs.append(f"towers.{t['id']}.fire_sound: BTD6 towers have no weapon sound of their own")
    for b in S["bloons"]["rows"]:
        if b["art"] == "none": errs.append(f"bloons.{b['id']}.art: needs a picture")
        if b["id"] in b["children"]: errs.append(f"bloons.{b['id']}.children: contains itself")
    rounds = sorted(r["round"] for r in S["rounds"]["rows"])
    if rounds != list(range(1, len(rounds) + 1)): errs.append(f"rounds: round numbers must run 1..N, got {rounds}")
    # code <-> hooks sheet
    fn_dir = os.path.join(MAIN, "functions")
    H = {r["id"]: r for r in S["hooks"]["rows"]}
    if os.path.isdir(fn_dir):
        files = {os.path.basename(f)[3:-4] for f in glob.glob(os.path.join(fn_dir, "fn_*.sqf"))}
        for h in H:
            if h != "initData" and h not in files: errs.append(f"hooks.{h}: functions/fn_{h}.sqf is missing (unimplemented)")
        for f in files - set(H): errs.append(f"functions/fn_{f}.sqf has no hooks row")
        code = ""
        for f in glob.glob(os.path.join(ROOT, "addons", "**", "*.sqf"), recursive=True):
            code += open(f).read()
        for m in set(re.findall(r"BTD_fnc_(\w+)", code)):
            if m not in H: errs.append(f"code calls BTD_fnc_{m}, which has no hooks row")
        for m in set(re.findall(r'remoteExec(?:Call)?\s*\[\s*"BTD_fnc_(\w+)"', code)):
            if m in H and H[m]["net"] == "none": errs.append(f"code calls BTD_fnc_{m} over the network, but its hooks row says net none")
        consts = ids(S["constants"])
        for m in set(re.findall(r'BTD_Const\s+get\s+"(\w+)"', code)):
            if m not in consts: errs.append(f"code reads constant {m!r}, which is not a constants row")
        for m in set(re.findall(r'playSound3?D?\s*\[?\s*"btdops_(\w+)"', code)):
            if m not in ids(S["sounds"]): errs.append(f"code plays sound btdops_{m}, which is not a sounds row")
    if not quiet:
        print(f"preflight: {len(SHEETS)} sheets, {sum(len(s['rows']) for s in S.values())} rows, {cells} cells checked")
        for e in errs: print("  FAIL", e)
        print("preflight:", "CLEAN" if not errs else f"{len(errs)} problem(s)")
    return errs


def verify_list(S):
    out = []
    for name, sh in S.items():
        for k, v in sh.get("verify", {}).items(): out.append(f"{name}.{k}: {v}")
    return out


# ---------------------------------------------------------------- generation
def sqf(v):
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return repr(round(v, 6)) if isinstance(v, float) else str(v)
    if isinstance(v, str): return '"' + v.replace('"', '""') + '"'
    if isinstance(v, list): return "[" + ",".join(sqf(x) for x in v) + "]"
    raise TypeError(v)


def struct(row, cols):
    """One row -> one SQF struct (a hashmap with one key per column)."""
    return "createHashMapFromArray [" + ",".join(f'["{c}",{sqf(row[c])}]' for c in cols) + "]"


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    old = open(path).read() if os.path.exists(path) else None
    if old != text:
        open(path, "w", newline="\n").write(text)
        print("  wrote", os.path.relpath(path, ROOT))


def gen(S):
    lines = [GEN_NOTE, "// One struct per sheet row.\n"]
    names = {"bloons": "BTD_Bloons", "towers": "BTD_Towers", "upgrades": "BTD_Upgrades", "rounds": "BTD_Rounds",
             "btd6_art": "BTD_Art", "sounds": "BTD_Sounds", "maps": "BTD_Maps"}
    for s, var in names.items():
        sh = S[s]; cols = list(sh["columns"])
        lines.append(f"{var} = createHashMap;\n")
        for r in sh["rows"]:
            lines.append(f'{var} set ["{r["id"]}", {struct(r, cols)}];\n')
    lines.append("BTD_Const = createHashMap;\n")
    for r in S["constants"]["rows"]:
        lines.append(f'BTD_Const set ["{r["id"]}", {sqf(r["value"])}];\n')
    order = lambda s: sqf([r["id"] for r in S[s]["rows"]])
    lines.append(f"BTD_TowerOrder = {order('towers')};\n")
    lines.append(f"BTD_RoundCount = {len(S['rounds']['rows'])};\n")
    write(os.path.join(MAIN, "functions", "fn_initData.sqf"), "".join(lines))

    # CfgFunctions
    fl = [GEN_NOTE, "class CfgFunctions {\n    class BTD {\n        tag = \"BTD\";\n        class core {\n",
          f'            file = "{PREFIX}\\main\\functions";\n']
    for h in S["hooks"]["rows"]:
        extra = " preInit = 1;" if h["hook"] == "preInit" else ""
        fl.append(f"            class {h['id']} {{{extra}}};\n")
    fl.append("        };\n    };\n};\n")
    write(os.path.join(MAIN, "CfgFunctions.hpp"), "".join(fl))

    # CfgSounds
    sl = [GEN_NOTE, "class CfgSounds {\n    sounds[] = {};\n"]
    for r in S["sounds"]["rows"]:
        if r["recipe"] == "none": continue
        db = r["volume_db"]
        sl.append(f'    class btdops_{r["id"]} {{ name = "btdops_{r["id"]}"; sound[] = {{"\\{PREFIX}\\main\\sounds\\{r["id"]}.ogg", {10 ** (db / 20):.3f}, 1, {max(r["range_m"],1)}}}; titles[] = {{}}; }};\n')
    sl.append("};\n")
    write(os.path.join(MAIN, "CfgSounds.hpp"), "".join(sl))

    # Build tablet buttons: one per tower row, ARMA left, BTD6 right
    tl = [GEN_NOTE]
    col = {"ARMA": 0, "BTD6": 0}
    for r in S["towers"]["rows"]:
        sec = r["section"]; i = col[sec]; col[sec] += 1
        x = "0.08" if sec == "ARMA" else "0.53"
        y = 0.20 + i * 0.085
        tl.append(f'class BTD_Btn_{r["id"]}: BTD_TabletButton {{ idc = {2100 + len(tl)}; x = "safeZoneX + safeZoneW * {x}"; '
                  f'y = "safeZoneY + safeZoneH * {y:.3f}"; text = "{r["name"]}  ${r["cost"]}"; '
                  f'action = "closeDialog 0; [\'{r["id"]}\'] call BTD_fnc_build;"; tooltip = "Range {r["range_m"]} m. Upgrade: {next(u["name"] for u in S["upgrades"]["rows"] if u["id"]==r["upgrade"])}"; }};\n')
    write(os.path.join(MAIN, "ui", "tablet_buttons.hpp"), "".join(tl))

    # Missions: remote-exec allowlist and mission.sqm per scenario
    re_l = [GEN_NOTE, "class CfgRemoteExec {\n    class Functions {\n        mode = 1;\n        jip = 0;\n"]
    for h in S["hooks"]["rows"]:
        if h["net"] == "server": re_l.append(f"        class BTD_fnc_{h['id']} {{ allowedTargets = 2; }};\n")
        if h["net"] == "clients": re_l.append(f"        class BTD_fnc_{h['id']} {{ allowedTargets = 0; }};\n")
    re_l.append("    };\n    class Commands { mode = 0; };\n};\n")
    m = S["maps"]["rows"][0]
    maxp = next(r["value"] for r in S["constants"]["rows"] if r["id"] == "max_players")
    for kind in ("solo", "coop", "selftest"):
        d = os.path.join(MISSIONS, f"btdops_{kind}.{m['world']}")
        write(os.path.join(d, "remoteexec.hpp"), "".join(re_l))
        write(os.path.join(d, "mission.sqm"), mission_sqm(m, maxp if kind == "coop" else 1, kind))
        write(os.path.join(d, "init.sqf"), GEN_NOTE + f'["{m["id"]}", "{kind}"] spawn BTD_fnc_start;\n')
        write(os.path.join(d, "description.ext"), DESCRIPTION.replace("@KIND@", kind))
        write(os.path.join(d, "map.hpp"), GEN_NOTE + f'#define BTD_MAP "{m["id"]}"\n#define BTD_MAX_PLAYERS {maxp if kind=="coop" else 1}\n#define BTD_MAP_NAME "{m["name"]}"\n')


DESCRIPTION = GEN_NOTE + """#include "map.hpp"
onLoadName = "Bloons TD Ops";
onLoadMission = "Glide anywhere, build Arma 3 and Bloons TD 6 towers, pop every bloon.";
author = "Bloons TD Ops";
briefing = 0;
debriefing = 1;
respawn = 3;
respawnDelay = 2;
respawnOnStart = -1;
disabledAI = 1;
joinUnassigned = 1;
enableDebugConsole = 1;
class Header {
    gameType = "Coop";
    minPlayers = 1;
    maxPlayers = BTD_MAX_PLAYERS;
};
#include "remoteexec.hpp"
"""


def mission_sqm(m, players, kind):
    cx, cy = m["center"]; sx, sy = m["spawn"]
    units = []
    for i in range(players):
        attr = "isPlayer=1;" if players == 1 else "isPlayable=1;"
        units.append(f"""				class Item{i}
				{{
					dataType="Object";
					class PositionInfo {{ position[]={{{cx+sx+i*2},5,{cy+sy}}}; angles[]={{0,1.5708,0}}; }};
					side="West";
					flags={7 if i == 0 else 5};
					class Attributes {{ {attr} name="btd_p{i+1}"; description="Bloon Defender {i+1}"; }};
					id={i+1};
					type="B_Soldier_F";
				}};
""")
    header = f'\tclass Header {{ gameType="Coop"; minPlayers=1; maxPlayers={players}; }};\n' if players > 1 else ""
    return f"""// GENERATED by tools/gen.py from sheets/maps.json
version=54;
class EditorData
{{
	moveGridStep=1;
	angleGridStep=0.2617994;
	scaleGridStep=1;
	autoGroupingDist=10;
	toggles=1;
	class ItemIDProvider {{ nextID={players+1}; }};
}};
binarizationWanted=0;
sourceName="btdops_{kind}";
addons[]={{"A3_Characters_F"}};
class AddonsMetaData
{{
	class List
	{{
		items=1;
		class Item0 {{ className="A3_Characters_F"; name="Arma 3 - Characters and Clothing"; author="Bohemia Interactive"; url="https://www.arma3.com"; }};
	}};
}};
randomSeed=4242;
class ScenarioData
{{
	author="Bloons TD Ops";
{header}}};
class Mission
{{
	class Intel
	{{
		timeOfChanges=1800.0002;
		startWeather=0.1;
		startWind=0.1;
		forecastWeather=0.1;
		forecastWind=0.1;
		forecastWaves=0.1;
		forecastLightnings=0.1;
		year=2035;
		month=6;
		day=24;
		hour=11;
		minute=0;
		startFogDecay=0.014;
		forecastFogDecay=0.014;
	}};
	class Entities
	{{
		items=1;
		class Item0
		{{
			dataType="Group";
			side="West";
			class Entities
			{{
				items={players};
{''.join(units)}			}};
			class Attributes {{}};
			id=0;
		}};
	}};
}};
"""


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "preflight"
    S = load()
    if cmd == "verify":
        for v in verify_list(S): print("  UNVERIFIED", v)
        sys.exit(0)
    if cmd == "gen":
        gen(S)  # generated files first, so preflight sees fn_initData etc.
    errs = preflight(S)
    v = verify_list(S)
    if v: print(f"preflight: {len(v)} cell(s) still need a check in the running game (python3 tools/gen.py verify)")
    sys.exit(1 if errs else 0)
