"""Arma 2: Operation Arrowhead edition: generated from the same sheets as the Arma 3 edition.

OA's SQF has no hashmaps, params, remoteExec, ctrlCreate or CfgFunctions-without-a-module, so each sheet row
becomes a plain array (a struct) whose fields are named by generated macros in data.hpp, refs become indexes,
the tablet's buttons are generated into a dialog class, and functions are compiled by a generated loader.
"""
import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OA = ROOT / "oa"
MAIN = OA / "addons" / "main"
FUNCS = MAIN / "functions"
MISSIONS = OA / "addons" / "missions"
PREFIX = r"\z\bloonsops_oa\addons\main"
SHEET_PREFIX = {"bloons": "B", "towers": "T", "upgrades": "U", "rounds": "R", "sounds": "S", "maps": "M", "oa_props": "P"}


def sqf(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return '"' + v.replace('"', '""') + '"'
    if isinstance(v, list):
        return "[" + ",".join(sqf(x) for x in v) + "]"
    raise TypeError(v)


def macro(s):
    return re.sub(r"[^A-Z0-9]", "_", s.upper())


def index_of(sheets, name):
    return {r["id"]: i for i, r in enumerate(sheets[name]["rows"])}


def row_values(sheets, name, row):
    out = []
    for c in sheets[name]["columns"]:
        if c["name"] == "status":
            continue
        v = row[c["name"]]
        if c["type"] in ("ref", "ref?"):
            v = index_of(sheets, c["ref"]).get(v, -1)
        elif c["type"] == "groups":
            idx = index_of(sheets, c["ref"])
            v = [[idx[g[0]]] + g[1:] for g in v]
        out.append(v)
    return out


def tex_paths(sheets):
    import sys
    sys.path.insert(0, str(ROOT / "tools"))
    from palette import TAN, WHITE, tex_name
    return {"tan": TAN, "white": WHITE}, tex_name


def generate(sheets):
    hdr = ["// GENERATED by tools/gen_oa.py from sheets/*.json - edit the sheets, not this file.",
           "// Each sheet row is an array; these macros name its fields and its rows."]
    for name, p in SHEET_PREFIX.items():
        cols = [c["name"] for c in sheets[name]["columns"] if c["name"] != "status"]
        for i, c in enumerate(cols):
            hdr.append(f"#define {p}_{macro(c)} {i}")
        if name != "rounds":
            for i, r in enumerate(sheets[name]["rows"]):
                hdr.append(f"#define {p}ROW_{macro(str(r['id']))} {i}")
    for i, r in enumerate(sheets["oa_props"]["rows"]):
        hdr.append(f"#define PROP_{macro(r['id'])} ((BO_OaProps select {i}) select P_CLASS)")
    for i, r in enumerate(sheets["economy"]["rows"]):
        hdr.append(f"#define CFG_{macro(r['id'])} (BO_Cfg select {i})")
    # extra per-tower fields appended after the sheet columns (painted textures)
    tcols = [c["name"] for c in sheets["towers"]["columns"] if c["name"] != "status"]
    hdr.append(f"#define T_BODY_TEX {len(tcols)}")
    hdr.append(f"#define T_ACCENT_TEX {len(tcols) + 1}")
    hdr.append(f'#define BO_PATH(f) ("{PREFIX}\\" + f)')
    (MAIN / "data.hpp").write_text("\n".join(hdr) + "\n")

    _, tex_name = tex_paths(sheets)
    out = ["// GENERATED by tools/gen_oa.py from sheets/*.json - edit the sheets, not this file.", ""]
    for name, p in SHEET_PREFIX.items():
        var = "BO_" + "".join(w.capitalize() for w in name.split("_"))
        rows = []
        for r in sheets[name]["rows"]:
            vals = row_values(sheets, name, r)
            if name == "towers":
                vals += [f"{PREFIX}\\data\\{tex_name(r['body_rgba'])}_co.paa", f"{PREFIX}\\data\\{tex_name(r['accent_rgba'])}_co.paa"]
            rows.append(sqf(vals))
        out.append(f"{var} = [\n  " + ",\n  ".join(rows) + "\n];")
    out.append("BO_Cfg = " + sqf([r["value"] for r in sheets["economy"]["rows"]]) + ";")
    out.append(f'BO_TexTan = "{PREFIX}\\data\\{tex_name([0.95, 0.78, 0.55, 1])}_co.paa";')
    out.append(f'BO_TexWhite = "{PREFIX}\\data\\{tex_name([1, 1, 1, 1])}_co.paa";')
    net = [h["id"] for h in sheets["oa_hooks"]["rows"] if h["net"]]
    out.append("BO_NetAllowed = " + sqf(["BO_fnc_" + n for n in net]) + ";")
    (FUNCS / "fn_initData.sqf").write_text("\n".join(out) + "\n")

    loader = ["// GENERATED by tools/gen_oa.py from sheets/oa_hooks.json. OA has no CfgFunctions without the",
              "// Functions module, so the mission compiles every function itself (init.sqf runs this first)."]
    for h in sheets["oa_hooks"]["rows"]:
        loader.append(f'BO_fnc_{h["id"]} = compile preprocessFileLineNumbers "{PREFIX}\\functions\\fn_{h["id"]}.sqf";')
    loader.append("call BO_fnc_initData;")
    (MAIN / "init_functions.sqf").write_text("\n".join(loader) + "\n")

    # tablet: one button per tower, ARMA column left, BTD column right
    ctl = ["// GENERATED by tools/gen_oa.py from sheets/towers.json", "class BO_TabletDialog {", "    idd = 77200;",
           "    movingEnable = 0;", "    class controlsBackground {",
           "        class Bg: BO_RscText { idc = -1; x = 0.08; y = 0.06; w = 0.84; h = 0.88; colorBackground[] = {0.05, 0.07, 0.05, 0.93}; text = \"\"; };",
           "    };", "    class controls {",
           "        class Title: BO_RscText { idc = 77201; x = 0.1; y = 0.08; w = 0.8; h = 0.06; sizeEx = 0.05; text = \"BUILD TABLET\"; colorText[] = {1, 0.85, 0, 1}; };",
           "        class HeadArma: BO_RscText { idc = -1; x = 0.1; y = 0.16; w = 0.38; h = 0.05; text = \"ARMA 2: OA\"; colorText[] = {0.72, 0.88, 0.48, 1}; };",
           "        class HeadBtd: BO_RscText { idc = -1; x = 0.52; y = 0.16; w = 0.38; h = 0.05; text = \"BLOONS TD\"; colorText[] = {1, 0.78, 0.25, 1}; };"]
    col = {"arma": 0, "btd": 0}
    for i, r in enumerate(sheets["towers"]["rows"]):
        sec = r["section"]
        x = 0.1 if sec == "arma" else 0.52
        y = 0.22 + col[sec] * 0.062
        col[sec] += 1
        bg = "{0.24, 0.32, 0.16, 0.95}" if sec == "arma" else "{0.7, 0.38, 0.06, 0.95}"
        ctl.append(f"        class Btn{i}: BO_RscButton {{ idc = {77300 + i}; x = {x}; y = {y:.3f}; w = 0.38; h = 0.055; "
                   f"text = {sqf(r['oa_name'] + '   $' + str(r['cost']))}; colorBackground[] = {bg}; "
                   f"tooltip = {sqf(r['blurb'])}; action = \"[{i}] call BO_fnc_tabletPick\"; }};")
    ctl += ["        class Hint: BO_RscText { idc = 77202; x = 0.1; y = 0.86; w = 0.62; h = 0.05; sizeEx = 0.03; text = \"Towers appear 4 m in front of you. Stay 5 m off the road.\"; };",
            "        class Close: BO_RscButton { idc = -1; x = 0.74; y = 0.86; w = 0.16; h = 0.055; text = \"Close\"; action = \"closeDialog 0\"; };",
            "    };", "};"]
    (MAIN / "tablet.hpp").write_text("\n".join(ctl) + "\n")

    snd = ["// GENERATED by tools/gen_oa.py from sheets/sounds.json (OA plays 3D sounds with say3D)", "class CfgSounds {", "    sounds[] = {};"]
    for s in sheets["sounds"]["rows"]:
        f = PREFIX + "\\" + s["file"]
        snd.append(f"    class bo_{s['id']} {{ name = \"bo_{s['id']}\"; sound[] = {{\"{f}\", {s['volume']}, 1}}; titles[] = {{}}; }};")
    snd.append("};")
    (MAIN / "sounds.hpp").write_text("\n".join(snd) + "\n")

    # copy shared generated media (sounds, painted textures) into the OA addon
    for sub in ("sounds", "data"):
        (MAIN / sub).mkdir(exist_ok=True)
        for f in (ROOT / "addons" / "main" / sub).glob("*"):
            if f.suffix in (".ogg", ".paa"):
                shutil.copy2(f, MAIN / sub / f.name)


def preflight(sheets, errors):
    for h in sheets["oa_hooks"]["rows"]:
        if not h["generated"] and not (FUNCS / f"fn_{h['id']}.sqf").exists():
            errors.append(f"oa_hooks[{h['id']}]: oa/addons/main/functions/fn_{h['id']}.sqf missing (unimplemented)")
    ids = {h["id"] for h in sheets["oa_hooks"]["rows"]}
    for f in FUNCS.glob("fn_*.sqf"):
        if f.stem[3:] not in ids:
            errors.append(f"{f.relative_to(ROOT)}: no oa_hooks row")
    used = set()
    for f in list(FUNCS.glob("*.sqf")) + list(MISSIONS.rglob("*.sqf")) + list(MAIN.glob("*.hpp")) + list(MAIN.glob("*.cpp")):
        used |= set(re.findall(r"BO_fnc_(\w+)", f.read_text()))
    for u in sorted(used - ids):
        errors.append(f"oa code calls BO_fnc_{u} but oa_hooks has no such row")
    for t in sheets["towers"]["rows"]:
        if t["kind"] in ("infantry", "static", "heli") and not t["oa_object_class"]:
            errors.append(f"towers[{t['id']}].oa_object_class: {t['kind']} needs an OA class")
        if t["kind"] in ("infantry", "static", "heli") and not t["oa_crew_class"]:
            errors.append(f"towers[{t['id']}].oa_crew_class: {t['kind']} needs an OA crew class")
        if t["kind"] in ("static", "heli") and not t["oa_turrets"]:
            errors.append(f"towers[{t['id']}].oa_turrets: {t['kind']} needs its gunner turret paths")
    for m in sheets["maps"]["rows"]:
        if m["edition"] != "oa":
            continue
        d = MISSIONS / m["mission_dir"]
        for need in ("mission.sqm", "description.ext", "init.sqf"):
            if not (d / need).exists():
                errors.append(f"{d.relative_to(ROOT)}/{need} missing")
