// GENERATED by tools/gen.py from sheets/*.json - edit the sheets, not this file.
class CfgSounds {
    sounds[] = {};
    class btdops_pop { name = "btdops_pop"; sound[] = {"\z\btdops\addons\main\sounds\pop.ogg", 1.000, 1, 80}; titles[] = {}; };
    class btdops_throw { name = "btdops_throw"; sound[] = {"\z\btdops\addons\main\sounds\throw.ogg", 0.631, 1, 50}; titles[] = {}; };
    class btdops_boom { name = "btdops_boom"; sound[] = {"\z\btdops\addons\main\sounds\boom.ogg", 1.000, 1, 150}; titles[] = {}; };
    class btdops_freeze { name = "btdops_freeze"; sound[] = {"\z\btdops\addons\main\sounds\freeze.ogg", 0.794, 1, 60}; titles[] = {}; };
    class btdops_place { name = "btdops_place"; sound[] = {"\z\btdops\addons\main\sounds\place.ogg", 0.794, 1, 40}; titles[] = {}; };
    class btdops_sell { name = "btdops_sell"; sound[] = {"\z\btdops\addons\main\sounds\sell.ogg", 0.794, 1, 40}; titles[] = {}; };
    class btdops_lose { name = "btdops_lose"; sound[] = {"\z\btdops\addons\main\sounds\lose.ogg", 1.000, 1, 1}; titles[] = {}; };
    class btdops_win { name = "btdops_win"; sound[] = {"\z\btdops\addons\main\sounds\win.ogg", 1.000, 1, 1}; titles[] = {}; };
    class btdops_round { name = "btdops_round"; sound[] = {"\z\btdops\addons\main\sounds\round.ogg", 0.708, 1, 1}; titles[] = {}; };
};
